worlds:

  # Stops the plugin from handling player positions in the specified worlds
  disable-coordinate-handling:
    - example-world
    - example-world2

  # Stops the plugin from handling player positions in the specified worlds or their sets, once they enter them.
  null-coordinates:
    - example-world3
    - example-world4

  # Configures the interval between global data saves. (Lower bound shadow-set to 1 minute)
  global-save-tick-interval: 6000


