name: AOSPlayerManager
version: 1.2.2
description: Tailor-Made plugin for the Age of Sauron Server, to manage player inventories and positions across worlds
author: MrKelpy
main: com.mrkelpy.aosplayermanager.AOSPlayerManager

commands:
  levellist:
    description: Displays a list of all the levels and level sets in the server.
    usage: /levellist

  checkdata:
    description: Opens a GUI to browse through the data for a player.
    usage: /checkdata [target player]

  savedata:
    description: Saves the data for all players, or for a player, to memory.
    usage: /savedata [(Optional) target player]